spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linkedin_denovo_localhost
    username: root
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: slava
    password: rvnjtp
    template:
      routing-key: test_queue

server:
  servlet:
    context-path: /api/v1/

app:
  scraping:
    batch-size: 5
  notifications:
    telegram:
      bot-token: 1708054968:AAEsZvyJUth4UI4EzjlkaKtw7uRQCIYFJ50
      chat-id: -1001493548628
    slack:
      slack-token: xoxb-1073218083651-1071671941189-NHmVi0hNMcQckY8RC2EQ0sCm
      notifications-channel: li_results_notifications
logging:
  level:
    sql: info
    web: info
#  notifications:
#    slack:
#      slack-token: xoxb-1073218083651-1071671941189-NHmVi0hNMcQckY8RC2EQ0sCm
#      notifications-channel: li_results_notifications
  search:
    service-url: [ URL ]

