spring:
  main:
    web-application-type: none

app:
  notification:
    telegram:
      bot-token: [BOT TOKEN]
      channel-id: [CHANNEL ID]
      enabled: false
  captcha:
    anti-captcha:
      token: [ANTI CAPTCHA TOKEN]
  chromedriver:
    path: [PATH TO CHROMEDRIVER EXECUTABLE]
    options:
      headless: true