INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (1, 'Keshav', 'Dimri', 'Sidley Austin LLP', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (2, 'Chris', 'Campbell', 'King & Spalding', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (3, 'David', 'Maysilles', 'King & Spalding', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (4, 'Beth', 'Berg', 'Sidley Austin LLP', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (5, 'Robert', 'Eckinger', 'Adams and Reese LLP', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (6, 'Phyllis', 'Sumner', 'King & Spalding', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (7, 'Heather', 'Vanderpool', 'King & Spalding', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (8, 'Samuel', 'Hipps', 'King & Spalding', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (9, 'Achim', 'Döser', 'King & Spalding', false, false, '');
INSERT INTO initial_data (denovo_id, first_name, last_name, firm_name, searched, no_results, middle_name) VALUES (10, 'Rob', 'Breunig', 'Adams and Reese LLP', false, false, '');
