app:
  chromedriver:
    path: [PATH]
    headless: false
  captcha:
    anti-captcha:
      token: [TOKEN]
  scraper:
    activities-amount: 50
  linkedin:
    profile-login: [LOGIN]
    profile-password: [PASSWORD]

spring:
  application:
    name: [NAME]
  rabbitmq:
    username: [USERNAME]
    password: [PASSWORD]
    listener:
      simple:
        prefetch: 0
        acknowledge-mode: none
      direct:
        prefetch: 0
    template:
      default-receive-queue: [QUEUE_NAME]