app:
  chromedriver:
    path: [ PATH TO CHROMADRIVER ]
    headless: false
  captcha:
    anti-captcha:
      token: [ TOKEN ]
  scraper:
    activities-amount: [ AMOUNT ] #default - 50
  linkedin:
    profile-login: [ LOGIN ]
    profile-password: [ PASSWORD ]
  notifications:
    telegram:
      bot-token: [ TOKEN ]
      chat-id: [ ID ]
    slack:
      slack-token: [ TOKEN ]
      notifications-channel: [ CHANNEL_NAME ]

spring:
  application:
    name: [ NAME ]
  rabbitmq:
    host: [ HOST ]
    port: [ PORT ]
    username: [ USERNAME ]
    password: [ PASSWORD ]
    listener:
      simple:
        prefetch: [ INT ] #default - 0
        acknowledge-mode: [ MODE ] #default - auto
    template:
      default-receive-queue: [ QUEUE ]