app:
  chromedriver:
    path: [ PATH ]
    headless: false
  captcha:
    anti-captcha:
      token: [ TOKEN ]
  scraper:
    activities-amount: 50
  linkedin:
    profile-login: [LOGIN]
    profile-password: [PASSWORD]

spring:
  application:
    name: [NAME]