spring:
  datasource:
    url: jdbc:postgresql://[HOST]:5493/denovo_linkedin
    username: dataox
    password: pdHMf3kN
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

app:
  search:
    minutes-for-one-task: 10
    retry-attempts: 10
    concurrency-restriction: 100
    user-agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36'
    required-results-count: 5
  notifications:
    telegram:
      bot-token: '1267422790:AAHiQcyTkqpPphUMP5SPNVWaXu1XXxJLtTQ'
      chat-id: -1001201576524
      enabled: true
  proxy:
    operia:
      key: 06931f4c8ef70f72
  scheduling:
    enabled: false
    search:
      not.searched.data: "0 * * * * *"